### ISSUE TITLE
RHEL7.4 certificate verify failed

### ISSUE THREAD

**Issue by andral** [arista-eosplus/pyeapi#149]
Hi there

After upgrading from RHEL 7.3 to 7.4 and pyeapi 0.7.0 to 0.8.1 I can't connect to a switch anymore getting the following error.
```
  File "build/bdist.linux-x86_64/egg/pyeapi/client.py", line 672, in enable
    **kwargs)
  File "build/bdist.linux-x86_64/egg/pyeapi/client.py", line 730, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyeapi/eapilib.py", line 495, in execute
    response = self.send(request)
  File "build/bdist.linux-x86_64/egg/pyeapi/eapilib.py", line 428, in send
    raise ConnectionError(str(self), error_msg)
ConnectionError: Socket error during eAPI connection: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```
Python version is 2.7.5 but there might me some backporting done by RedHat which I think is the issue here because the version number does not actually represent the expected functionality regarding SSL.
If I remove the following two lines it works fine.
https://github.com/arista-eosplus/pyeapi/blob/release-0.8.1/pyeapi/eapilib.py#L67-L68

And here's my code:
```python
try:
    self.node = pyeapi.connect(host=self.host,
                               port=self.port,
                               username=self.user,
                               password=self.pswd,
                               transport=self.prot,
                               return_node=True)
except AttributeError as e:
    self.exitme('Connection parameter not defined: {err}'
                .format(err=e))
```

How can I disable certificate verification?
Any help would be appreciated, thanks!

Regards

**Comment by mharista** [comment]
Hi @andral,

You are right that RedHat has made some changes to how certificates are handled in the python 2.7.5 they ship. They have had the ability to enable https certificate verification since RHEL7.2, but it was disabled by default. In RHEL 7.4 they changed the default behavior for certs to be enabled, hence your breakage.

You can disable the default certificate verification by editing the cert-verification.cfg file in RedHat or by setting the PYTHONHTTPSVERIFY environment variable to 0.

More information/details here: https://access.redhat.com/articles/2039753#red-hat-enterprise-linux-7-resolution-4

Please try one of these options out and let me know if it resolves your issue.

Thanks,
Matt

**Comment by andral** [comment]
Hey @mharista 
Thanks a lot for your quick response and the suggested workarround! I tried both and the work just fine. I did however add the following in my code before importing pyeapi.

```python
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)):
  ssl._create_default_https_context = ssl._create_unverified_context
```

This way I don't have to fiddle arround with the servers the code's running on.

Cheers!

**Comment by mharista** [comment]
@andral Good to hear and thanks for adding the additional code snippet here. I'm going to close this issue as it is a RedHat specific issue with several workarounds available.
