### ISSUE TITLE
How to execute ``reload`` (to reboot the device)

### ISSUE THREAD

**Issue by mirceaulinic** [arista-eosplus/pyeapi#163]
Hello,

I've been searching in the documentation http://pyeapi.readthedocs.io/en/latest/index.html, and briefly looked through the code, but I couldn't find a way to be able to reboot the switch (necessary after an OS upgrade). Is this something achievable via pyeapi? Thanks!

**Comment by dathelen** [comment]
@mirceaulinic 

If you pass the command ```reload now``` this will reload without having the user confirm it.  Just have to be careful your startup-config is what you expect to be because the safety net that is normal there in EOS passed-by when you use the ```now``` parameter.   Or alternatively you could do something like ```reload force in <x> minutes```, in case you want to give yourself a buffer

HTH

**Comment by mirceaulinic** [comment]
Thank you very much @dathelen!
