### ISSUE TITLE
pyeapi.client.connect_to(node) should not raise KeyError if node is missing form the config

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/pyeapi#3]
I think a more intuitive error message would be better: MissingNodeConfigurationError?

**Comment by privateip** [comment]
v0.1.1 added a new string message that is returned from connect_to that specifies the configuration name could not be found.  The call to connect_to still raises an AttributeError.  I'm not convinced we need a custom exception for this error.  The updated string should help with understanding the root cause for the error.
